version: "3"
services:
 app:
   restart: always
   image: emission:latest
   ports:
     - 3000:3000
   env_file:
     - .env.example
   volumes:
     - /data/app/uploads/:/home/node/app/public/uploads
   networks:
     - emission_network
  
 database:
   restart: always
   image: postgres:12-alpine
   environment:
     POSTGRES_USER: emission_user
     POSTGRES_PASSWORD: emission_pass
     POSTGRES_DB: emissions
   volumes:
     - /data/postgresql:/var/lib/postgresql/data/
   networks:
     - emission_network

networks:
 emission_network:
   external: true